[workspace]
members = [
  "derive",
]

[package]
name = "ck3-mod-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
encoding = "0.2"
fnv = "1"
home = "0.5"
image = "0.24"
itertools = "0.10"
lazy_static = "1"
thiserror = "1"
walkdir = "2"

ck3-mod-validator_derive = { version = "0.1", path = "derive" }

[target.'cfg(windows)'.dependencies]
winreg = "0.10"
