[workspace]
members = [
  "derive",
]

[package]
name = "ck3-mod-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3.2.12", features = ["derive"] }
fnv = "1.0.7"
home = "0.5"
thiserror = "1.0"
walkdir = "2"

ck3-mod-validator_derive = { version = "0.1", path = "derive" }

[target.'cfg(windows)'.dependencies]
winreg = "0.10"
