[package]
name = "ck3-mod-validator_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-crate = "1.2"
proc-macro-error = "1.0"
quote = "1.0"
syn = "1.0"
